@echo off
REM ============================================================================
REM HPC Setup Script for Windows
REM Negative Space Imaging Project
REM Copyright (c) 2025 Stephen Bilodeau. All rights reserved.
REM ============================================================================
REM This script sets up the HPC environment for the Negative Space Imaging Project.
REM ============================================================================

setlocal enabledelayedexpansion

REM Configuration
set PYTHON_MIN_VERSION=3.9
set VENV_DIR=%~dp0.venv-hpc
set LOG_FILE=%~dp0hpc_setup.log

REM Initialize
echo ============================================== > "%LOG_FILE%"
echo HPC Setup Log - %DATE% %TIME% >> "%LOG_FILE%"
echo ============================================== >> "%LOG_FILE%"

echo ==============================================
echo Negative Space Imaging Project
echo HPC Setup Script for Windows
echo ==============================================
echo.

REM Check Python
echo [INFO] Checking Python version...
python --version 2>nul
if errorlevel 1 (
    echo [ERROR] Python not found. Please install Python %PYTHON_MIN_VERSION%+
    exit /b 1
)

for /f "tokens=2" %%i in ('python --version 2^>^&1') do set PYTHON_VERSION=%%i
echo [OK] Python %PYTHON_VERSION% found

REM Check CUDA
echo [INFO] Checking CUDA availability...
nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>nul
if errorlevel 1 (
    echo [WARN] CUDA not available. GPU acceleration will be disabled.
    set HAS_CUDA=false
) else (
    echo [OK] CUDA available
    set HAS_CUDA=true
)

REM Create virtual environment
echo [INFO] Creating virtual environment...
if exist "%VENV_DIR%" (
    echo [WARN] Virtual environment already exists
    set /p RECREATE="Do you want to recreate it? (Y/N): "
    if /i "!RECREATE!"=="Y" (
        rmdir /s /q "%VENV_DIR%"
    ) else (
        echo [INFO] Using existing virtual environment
        goto :activate_venv
    )
)

python -m venv "%VENV_DIR%"
echo [OK] Virtual environment created at %VENV_DIR%

:activate_venv
echo [INFO] Activating virtual environment...
call "%VENV_DIR%\Scripts\activate.bat"
if errorlevel 1 (
    echo [ERROR] Failed to activate virtual environment
    exit /b 1
)
echo [OK] Virtual environment activated

REM Upgrade pip
echo [INFO] Upgrading pip...
python -m pip install --upgrade pip setuptools wheel

REM Install base requirements
echo [INFO] Installing base requirements...
if exist "%~dp0requirements.txt" (
    pip install -r "%~dp0requirements.txt"
    echo [OK] Base requirements installed
) else (
    echo [WARN] requirements.txt not found
)

REM Install HPC requirements
echo [INFO] Installing HPC requirements...

pip install dask[distributed]>=2023.1.0
pip install ray>=2.5.0
pip install aiohttp>=3.8.0
pip install pyarrow>=12.0.0
pip install prefect>=2.10.0
pip install prometheus-client>=0.17.0
pip install psutil>=5.9.0

if "%HAS_CUDA%"=="true" (
    echo [INFO] Installing CUDA packages...
    pip install cupy-cuda12x 2>nul
    if not errorlevel 1 (
        echo [OK] CUDA packages installed
    ) else (
        echo [WARN] Failed to install CUDA packages
    )
)

echo [OK] HPC requirements installed

REM Configure environment
echo [INFO] Configuring HPC environment...

(
echo # HPC Environment Configuration
echo # Generated by setup_hpc.bat on %DATE%
echo.
echo # Cluster settings
echo HPC_BACKEND=auto
echo HPC_CLUSTER_NAME=negative-space-hpc
echo HPC_ENVIRONMENT=development
echo.
echo # Resource defaults
echo HPC_DEFAULT_CPUS=4
echo HPC_DEFAULT_MEMORY_GB=16
echo HPC_DEFAULT_WALL_TIME=04:00:00
echo.
echo # GPU settings
echo HPC_GPUS_ENABLED=%HAS_CUDA%
echo.
echo # Logging
echo HPC_LOG_LEVEL=INFO
) > "%~dp0.env.hpc"

echo [OK] Environment configuration created

REM Validate installation
echo [INFO] Validating HPC installation...

python -c "import dask; import ray; import aiohttp; import pyarrow; print('[OK] Core HPC packages verified')"
if errorlevel 1 (
    echo [ERROR] Package verification failed
    exit /b 1
)

REM Print summary
echo.
echo ==============================================
echo HPC Setup Complete
echo ==============================================
echo.
echo Virtual Environment: %VENV_DIR%
echo CUDA Support: %HAS_CUDA%
echo.
echo To activate the HPC environment:
echo   %VENV_DIR%\Scripts\activate.bat
echo.
echo To run HPC examples:
echo   python hpc_integration_example.py
echo.

echo [INFO] Setup completed successfully!
echo Setup completed successfully >> "%LOG_FILE%"

endlocal
