# Data Processing Service Configuration
# © 2025 Negative Space Imaging, Inc. - CONFIDENTIAL

apiVersion: v1
kind: Service
metadata:
  name: quantum-processing-service
  namespace: negative-space-system
  labels:
    app: quantum-processor
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: quantum-processor
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quantum-processor-hpa
  namespace: negative-space-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: quantum-processor
  minReplicas: 5
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 5
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
