# Quantum Data Processing Pipeline Configuration
# © 2025 Negative Space Imaging, Inc. - CONFIDENTIAL

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quantum-processor
  namespace: negative-space-system
spec:
  serviceName: quantum-processing
  replicas: 5
  selector:
    matchLabels:
      app: quantum-processor
  template:
    metadata:
      labels:
        app: quantum-processor
    spec:
      containers:
      - name: quantum-engine
        image: negative-space/quantum-processor:latest
        resources:
          limits:
            cpu: "32"
            memory: "64Gi"
            nvidia.com/gpu: "4"
          requests:
            cpu: "16"
            memory: "32Gi"
            nvidia.com/gpu: "2"
        env:
        - name: QUANTUM_BACKEND
          value: "IBM-Q"
        - name: MAX_QUBITS
          value: "127"
        - name: ERROR_CORRECTION
          value: "surface-code"
        - name: OPTIMIZATION_LEVEL
          value: "3"
        volumeMounts:
        - name: quantum-storage
          mountPath: /data
        - name: quantum-cache
          mountPath: /cache
        ports:
        - containerPort: 9000
          name: grpc
        - containerPort: 9090
          name: metrics
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
  volumeClaimTemplates:
  - metadata:
      name: quantum-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "premium-ssd"
      resources:
        requests:
          storage: 1000Gi
  - metadata:
      name: quantum-cache
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "premium-ssd-cached"
      resources:
        requests:
          storage: 500Gi
