# Data Processing Pipeline Configuration
# © 2025 Negative Space Imaging, Inc. - CONFIDENTIAL

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: negative-space-processing
  namespace: negative-space-system
spec:
  entrypoint: negative-space-processing
  templates:
  - name: negative-space-processing
    dag:
      tasks:
      - name: data-ingestion
        template: data-ingestion
      - name: quantum-preprocessing
        dependencies: [data-ingestion]
        template: quantum-preprocessing
      - name: quantum-processing
        dependencies: [quantum-preprocessing]
        template: quantum-processing
      - name: post-processing
        dependencies: [quantum-processing]
        template: post-processing
      - name: result-aggregation
        dependencies: [post-processing]
        template: result-aggregation

  - name: data-ingestion
    container:
      image: negative-space/data-ingestion:latest
      command: [python, /app/ingest.py]
      resources:
        requests:
          memory: "4Gi"
          cpu: "2"
        limits:
          memory: "8Gi"
          cpu: "4"

  - name: quantum-preprocessing
    container:
      image: negative-space/quantum-preprocessor:latest
      command: [python, /app/preprocess.py]
      resources:
        requests:
          memory: "16Gi"
          cpu: "8"
        limits:
          memory: "32Gi"
          cpu: "16"

  - name: quantum-processing
    container:
      image: negative-space/quantum-processor:latest
      command: [python, /app/process.py]
      resources:
        requests:
          memory: "32Gi"
          cpu: "16"
          nvidia.com/gpu: "2"
        limits:
          memory: "64Gi"
          cpu: "32"
          nvidia.com/gpu: "4"

  - name: post-processing
    container:
      image: negative-space/post-processor:latest
      command: [python, /app/postprocess.py]
      resources:
        requests:
          memory: "16Gi"
          cpu: "8"
        limits:
          memory: "32Gi"
          cpu: "16"

  - name: result-aggregation
    container:
      image: negative-space/result-aggregator:latest
      command: [python, /app/aggregate.py]
      resources:
        requests:
          memory: "8Gi"
          cpu: "4"
        limits:
          memory: "16Gi"
          cpu: "8"
