apiVersion: apps/v1
kind: Deployment
metadata:
  name: negative-space-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: negative-space-ml-processor
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ml-processor
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: negative-space-web-viewer
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: web-viewer
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
