# HPA and VPA Configuration
# © 2025 Negative Space Imaging, Inc. - CONFIDENTIAL

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: negative-space-hpa
  namespace: negative-space-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: negative-space-core
  minReplicas: 100
  maxReplicas: 1000
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: negative-space-vpa
  namespace: negative-space-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: negative-space-core
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: "1"
        memory: "2Gi"
      maxAllowed:
        cpu: "8"
        memory: "16Gi"
