# Scaling Configuration
# © 2025 Negative Space Imaging, Inc. - CONFIDENTIAL

version: '1.0'

global:
  max_concurrent_operations: 1000000
  auto_scaling: true
  region_distribution: global

compute:
  initial_nodes: 100
  max_nodes: unlimited
  scaling_threshold: 75
  cooldown_period: 60
  node_types:
    - type: cpu-optimized
      min_count: 50
    - type: gpu-optimized
      min_count: 25
    - type: memory-optimized
      min_count: 25

storage:
  type: distributed
  replication_factor: 3
  sharding:
    enabled: true
    shards: auto
  backup:
    frequency: real-time
    retention: 90d

memory:
  cache_strategy: distributed
  redis_clusters: 5
  max_memory: 80%

database:
  type: distributed
  read_replicas: 5
  write_nodes: 3
  auto_scaling:
    enabled: true
    max_instances: unlimited

network:
  cdn:
    enabled: true
    points_of_presence: global
  load_balancing:
    algorithm: least_connections
    health_checks: true
  ddos_protection: true

monitoring:
  metrics_retention: 365d
  alert_threshold: 80%
  auto_remediation: true
