# Analysis Pipeline Configuration
# © 2025 Negative Space Imaging, Inc. - CONFIDENTIAL

version: '1.0'

analysis:
  quantum_analysis:
    state_tomography: true
    entanglement_measures: true
    coherence_metrics: true
    noise_characterization: true
    error_correction_analysis: true

  classical_analysis:
    signal_processing:
      fourier_transform: true
      wavelet_analysis: true
      correlation_functions: true
    statistical_analysis:
      hypothesis_testing: true
      confidence_intervals: true
      bayesian_inference: true

  hybrid_analysis:
    quantum_classical_interface:
      enabled: true
      optimization: "adaptive"
    feature_extraction:
      quantum_signatures: true
      classical_patterns: true
      hybrid_patterns: true

machine_learning:
  models:
    - type: "quantum_neural_network"
      layers: 16
      qubits_per_layer: 127
      optimization: "quantum_aware"
    - type: "classical_cnn"
      architecture: "densenet201"
      transfer_learning: true
    - type: "hybrid_network"
      quantum_layers: 8
      classical_layers: 12

visualization:
  plots:
    - type: "quantum_state"
      dimensions: 4
      interactive: true
    - type: "classical_correlation"
      type: "3D"
      real_time: true
    - type: "hybrid_analysis"
      type: "multi_dimensional"
      projection: "adaptive"

output:
  formats:
    - type: "hdf5"
      compression: "gzip"
    - type: "parquet"
      compression: "snappy"
    - type: "quantum_format"
      encryption: "quantum_resistant"

performance:
  distributed_processing: true
  gpu_acceleration: true
  quantum_acceleration: true
  memory_optimization: true
  cache_strategy: "intelligent"
