groups:
- name: NegativeSpaceAlerts
  rules:
  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High Memory Usage (instance {{ $labels.instance }})"
      description: "Memory usage is above 85% for 5 minutes\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU Usage (instance {{ $labels.instance }})"
      description: "CPU usage is above 90% for 5 minutes\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: APIServiceDown
    expr: up{job="api"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "API Service Down (instance {{ $labels.instance }})"
      description: "API service is down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: DatabaseDown
    expr: up{job="postgres"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Database Down (instance {{ $labels.instance }})"
      description: "PostgreSQL database is down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: SlowHTTPResponses
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job="api"}[5m])) by (le, handler)) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Slow HTTP Responses (instance {{ $labels.instance }})"
      description: "HTTP requests are taking more than 1s (95th percentile)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HighDatabaseConnections
    expr: pg_stat_activity_count{datname="sovereign"} > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High Database Connections (instance {{ $labels.instance }})"
      description: "Database has more than 100 active connections\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High Error Rate (instance {{ $labels.instance }})"
      description: "Error rate is above 5% for 5 minutes\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
